## The two below functions can be used to store a matrix in a function
## and retrieve the inverse of it's calculation, without having to do the
## inverse calculation twice. 
## 
## The functions work by firstly calling the makeCacheMatrix function and
## storing it to a variable. ie. 
## myMatrix <- makeCacheMatrix(matrix(c(1,2,3,0),nrow=2))
## 
## Followed by calling cacheSolve() function which will return the 
## previously worked out inverse of the matrix stored in myMatrix 
## variable, or working it out if it wasn't cached. 


makeCacheMatrix <- function(m = matrix()) {
        ## This functions creates a variable with 4 Functions within, used for the purpose
        ## of storing and caching a matrix and it's inverse
        ## 
        ## setMatrix() overwrites the value of the matrix m in the parent environment
        ## getMatrix() retrieves the value of the matrix from the parent envrionment
        ## setInverse() saves the value of the inverse to the value I in paren environment
        ## gerInverse() retreives the value of the inverse from the parent envrionment
        
        I <- NULL 
        setMatrix <- function(y) {
                m <<- y
                I <<- NULL
        }
        getMatrix <- function() m
        setInverse <- function(inverse) I <<- inverse
        getInverse <- function() I
        list(setMatrix = setMatrix, getMatrix = getMatrix,
             setInverse = setInverse,
             getInverse = getInverse)
}

cacheSolve <- function(x, ...) {
        ## This function is to be used in conjuction with makeCacheMatrix where x is a variable
        ## generated by said function. 
        ## This function will call the x variable and check if the inverse of the function was 
        ## previously stored. If the inverse is successfully retrieved, the function returns the
        ## inverse and terminates. Otherwise the function retrieves the matrix from the x variable, 
        ## and works out the inverse, followed by storing it back in the variable created by the 
        ## makeCacheMatrix function. 
        
        I <- x$getInverse()
        if(!is.null(I)) {
                message("getting cached data")
                return(I)
        }
        data <- x$getMatrix()
        I <- solve(data)
        x$setInverse(I)
        I
}